# Generated by Django 4.0.1 on 2022-01-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('pageCount', models.IntegerField(null=True)),
                ('thumbnailUrl', models.CharField(max_length=256, null=True)),
                ('shortDescription', models.CharField(max_length=256, null=True)),
                ('longDescription', models.TextField(null=True)),
            ],
        ),
    ]
